apiVersion: v1
kind: Service
metadata:
  name: vllm-sim-prefill-service
spec:
  selector:
    llm-d.ai/role: prefill
  ports:
    - name: http
      port: 8000
      targetPort: modelserver
      protocol: TCP
  type: ClusterIP