apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: llm-d-optimized-baseline
resources:
  - deployment.yaml
  - service.yaml

labels:
  - pairs:
      llm-d.ai/guide: optimized-baseline
      llm-d.ai/role: decode
      llm-d.ai/model: Qwen2.5-0.5B-Instruct
    includeSelectors: true
    includeTemplates: true