apiVersion: v1
kind: Service
metadata:
  name: modelserver-sim
spec:
  selector:
    app.kubernetes.io/name: modelserver-sim
  ports:
    - name: modelserver
      port: 8000
      protocol: TCP
      targetPort: modelserver